export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';
export const FETCH_IN_THEATRES = 'FETCH_IN_THEATRES';
export const GET_MOVIE = 'GET_MOVIE';

export const SELECTED_MOVIE = 'SELECTED_MOVIE';

/*
* Autosuggest
*/

export const UPDATE_INPUT_VALUE = 'UPDATE_INPUT_VALUE';
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS';
export const UPDATE_SUGGESTIONS = 'UPDATE_SUGGESTIONS';
export const LOAD_SUGGESTIONS_BEGIN = 'LOAD_SUGGESTIONS_BEGIN';
